eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8771

spring:
  application:
    name: eshop-product-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://192.168.33.11:3306/eshop
    username: root
    password: Pengzhikang123456.
  rabbitmq:
    host: 192.168.33.11
    port: 5672
    username: rabbitadmin
    password: 123456
    virtual-host: /